# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyobjectwork',
            name='status',
            field=models.CharField(choices=[('conveersation', 'переговоры'), ('treaty', 'договор'), ('key_money', 'аванс'), ('in_work', 'в работе'), ('done', 'выполнено'), ('payment', 'оплата'), ('completed', 'завершен')], default='', max_length=100, verbose_name='Статус работы'),
            preserve_default=False,
        ),
    ]
