# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
