# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20180518_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='order',
            new_name='owner',
        ),
    ]
