# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20180522_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcompany',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Комментарий'),
        ),
    ]
