# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20180522_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='company_object_contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_object_contact', to='firstapp.CompanyObject'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
