# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20180530_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyobject',
            old_name='order_obj',
            new_name='owner_obj',
        ),
    ]
