# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0013_auto_20180530_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('moder', models.BooleanField(default=False)),
                ('company_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.CompanyObject')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий объекту',
                'verbose_name_plural': 'Комментарии объектов',
            },
        ),
        migrations.AlterModelOptions(
            name='commentcompany',
            options={'verbose_name': 'Комментарий организации', 'verbose_name_plural': 'Комментарии организаций'},
        ),
        migrations.AlterField(
            model_name='commentcompany',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Комментарий'),
        ),
    ]
