# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20180602_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='company_object_contact',
        ),
    ]
