# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_auto_20180604_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcontact',
            name='company_object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='firstapp.CompanyObject'),
            preserve_default=False,
        ),
    ]
