# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-15 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_objectcontact_company_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyobjectwork',
            name='user_work',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
