# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_auto_20180615_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=80, verbose_name='Ф.И.О.')),
                ('position', models.CharField(max_length=80, verbose_name='Должность')),
                ('tel', models.CharField(max_length=80, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контактные лица к работе',
                'verbose_name_plural': 'Контактыне лица к работе',
            },
        ),
        migrations.AlterField(
            model_name='companyobjectwork',
            name='status',
            field=models.CharField(choices=[('переговоры', 'переговоры'), ('договор', 'договор'), ('аванс', 'аванс'), ('в работе', 'в работе'), ('выполнено', 'выполнено'), ('оплата', 'оплата'), ('завершен', 'завершен')], max_length=100, verbose_name='Статус работы'),
        ),
        migrations.AddField(
            model_name='contactwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.CompanyObjectWork'),
        ),
    ]
