# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import firstapp.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0021_commentwork_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('протокол', 'протокол'), ('договор', 'договор')], max_length=100, verbose_name='Тип документа')),
                ('document', models.FileField(upload_to='work/documents/', validators=[firstapp.validators.validate_file_extension])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.CompanyObjectWork')),
            ],
            options={
                'verbose_name': 'Прикрепленный документ',
                'verbose_name_plural': 'Прикрепленные документы',
            },
        ),
    ]
