# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-25 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_remove_documentwork_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentwork',
            old_name='document',
            new_name='file',
        ),
    ]
