# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-26 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_auto_20180625_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatar/'),
        ),
    ]
