# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_auto_20180626_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectcontact',
            name='object_contact',
        ),
        migrations.AddField(
            model_name='objectcontact',
            name='object_contact',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='firstapp.CompanyContact'),
            preserve_default=False,
        ),
    ]
