# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-12 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_auto_20180703_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_fio',
            field=models.CharField(max_length=300, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(max_length=300, verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=300, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(max_length=300, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='commentcompany',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='commentobject',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='commentwork',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='company',
            name='actual_adress',
            field=models.CharField(max_length=300, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='position',
            field=models.CharField(max_length=300, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='tel',
            field=models.CharField(max_length=300, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='companyobject',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='companyobjectwork',
            name='user_work',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='companyobjectwork',
            name='work',
            field=models.CharField(max_length=300, verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='contactwork',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='contactwork',
            name='position',
            field=models.CharField(max_length=300, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='contactwork',
            name='tel',
            field=models.CharField(max_length=300, verbose_name='Телефон'),
        ),
    ]
